### ISSUE TITLE
Show invisibles/indent guides issue

### ISSUE THREAD

**Issue by KeitIG** [jawee/language-blade#10]
Hi !

I found a bug with indent guides, 

when the extension is enabled:
![capture du 2015-01-15 14 06 56](https://cloud.githubusercontent.com/assets/1311607/5757904/3ba9470e-9cc0-11e4-9e1e-7ec921f4968a.png)

After disabling it:
![capture du 2015-01-15 14 08 14](https://cloud.githubusercontent.com/assets/1311607/5757907/42404f9a-9cc0-11e4-9888-902f4d8d55b2.png)

There is a little space character playing with us at lines starts there :)

**Comment by jawee** [comment]
@KeitIG Could you provide me with the code that has the issue for you? I cannot reproduce it with my test files.

**Comment by KeitIG** [comment]
Sure: 

```blade
@foreach ($campaigns as $i=>$campaign)
    @if (!$campaign->archived)
        <!-- blabla -->
    @else
        <a class="label label-warning" href="{{ action('CampaignController@unArchive', array($campaign->id)) }}">{{trans('pages.unarchive')}}</a>
    @endif
    <a class="label label-danger action_confirm" href="{{ action('CampaignController@destroy', array($campaign->id)) }}" data-method="delete">{{trans('pages.actiondelete')}}</a>
@endforeach
```

I'm using atom 0.184 on a ubuntu-based distro.
