### ISSUE TITLE
[Feature] Laravel 5 new syntax support

### ISSUE THREAD

**Issue by tortuetorche** [jawee/language-blade#13]
Can you support the new raw HTML output of Blade in Laravel 5, please?

```
{!! Form::open() !!}
```

You can read the Laravel 5 Templates [doc](http://laravel.com/docs/5.0/templates#other-blade-control-structures) for more information.

**Comment by jawee** [comment]
Did you update the package in atom? I published a new version yesterday that should contain the feature.

**Comment by tortuetorche** [comment]
I think, I've the 0.11.0 version but looks this screenshot the closed curly bracket isn't well colorized.

![atom_blade_laravel_5](https://cloud.githubusercontent.com/assets/5038872/6480531/093b536a-c255-11e4-8d99-91e35f95f586.png)

**Comment by tortuetorche** [comment]
By the way your package is very useful, many thanks!

**Comment by jawee** [comment]
You should thank the contributors, I don't really do anything more than maintaining this. :) I will try to fix that problem, not sure when though.

**Comment by tortuetorche** [comment]
I've open a pull request to fix this bug can you review it or maybe @slayerfat?

**Comment by jawee** [comment]
It seemed like it worked, published new version. :)

**Comment by tortuetorche** [comment]
Great, thank you for your time.

And have a good day!
