### ISSUE TITLE
Example of broken highlighting

### ISSUE THREAD

**Issue by Stanzilla** [jawee/language-blade#18]
![2015-05-07_19-02-47](https://cloud.githubusercontent.com/assets/75278/7521131/c0d8022a-f4eb-11e4-8c47-9ce73824f4dc.png)

I think the foreach breaks it

**Comment by Ingramz** [comment]
Could you post the same code as plain text?

**Comment by Stanzilla** [comment]
Ahh, nevermind man, sorry. I fkd up, missed a " there :(
