### ISSUE TITLE
Recognising Blade files

### ISSUE THREAD

**Issue by alexrussell** [jawee/language-blade#2]
I know this issue kinda came up in #1 and I mentioned that I had some issues with the language actually kicking in for blade files.

Here's what I've noticed:

- If I open a Blade file (e.g. `xyz.blade.php`) I've never opened it opens as a PHP file
- If I then switch the syntax to Blade manually it's fine
- If I then close the file and reopen it another time 9doesn't have to be immediately) it appears to remember it's a Blade file
- But still, other new unopened Blade files (e.g. `abc.blade.php`) open as PHP

Also (and pretty obviously), if I have previously switch a file's view mode to Blade so that it no re-opens in blade, I can then change it to PHP so that form now on it opens as PHP.

Is this just me or it is a bug? I know you at one point [changed](https://github.com/jawee/language-blade/commit/a331776dddcfad933c7d62252362be11bb6c1c3d) the `fileTypes` config setting to fix an issue with highlighting, but it still appears to be around for me. But maybe there's something I'm doing weird. So first of all it'd be nice to get confirmation, and then if no-one else has the same issue, see if there's a package I have that's sending if funny. Does Atom have any debugging mode/command to enable us to see the decision behind a syntax setting decision?

**Comment by Ingramz** [comment]
I forgot to mention this earlier. As a permanent-temporary solution to force all .blade.php and .php files to be opened with correct grammar, you can use the script from following post. It has to be inserted into your personal init script.

https://discuss.atom.io/t/edit-set-file-associations/2650/12

**Comment by vinkla** [comment]
Any update on this?

**Comment by Ingramz** [comment]
@vinkla it's still not possible without some external helper. If you don't like using the script I posted, there is [file-types](https://atom.io/packages/file-types) package which does essentially the same thing.

**Comment by vinkla** [comment]
@Ingramz would it be possible to use that package as a dependency?

**Comment by Ingramz** [comment]
@vinkla probably not as it requires some configuration after installation. It would be easier to include the smaller script so that it would be executed each time a file is opened.

If you need this only for yourself, I think you are better off by applying the init script fix until someone fixes this in Atom core.

**Comment by vinkla** [comment]
Okay, thanks!

**Comment by Ingramz** [comment]
I took some time to look into the issue and now there is a PR in atom core awaiting to be merged, which should solve all problems with file type detection in PHP and Blade. In case it gets merged soon, it should land stable in a month or so.

**Comment by vinkla** [comment]
@Ingramz :+1:

**Comment by Ingramz** [comment]
Fixed in atom 1.4.0 beta 0

**Comment by vinkla** [comment]
Awesome!
