### ISSUE TITLE
{{ $something }} highlighting broken inside HTML parameters

### ISSUE THREAD

**Issue by Ingramz** [jawee/language-blade#21]
Using "Atom Dark" theme:
![source_hack](https://cloud.githubusercontent.com/assets/1017132/7955528/aee499c4-09e1-11e5-9296-aaf274906282.png)

The reason why the first `}` is colored differently is because it's nearest class is `source`, which is/was required to get autocomplete to detect scope in situations where the cursor is right before the ending brace. With recent improvements to autocomplete, it needs to investigated whether we need the hack anymore or should we go with PHP-s solution where a workaround has been applied (https://github.com/atom/atom-dark-syntax/blob/master/index.less#L179) - that would change the color of the curly braces.

**Comment by Ingramz** [comment]
Autocomplete uses the same ctrl+alt+shift+p scope names at cursor, which means that currently it's not possible to achieve the desired effect without a grammar scope dedicated to the right side character from the cursor. This is because first-mate only outputs tokens for characters and does not allow for *zero-width* tokens. These tokens could be the solution for more accurate cursor scopes.

It is also pretty much impossible to please everyone with the choice of scope names for those opening and closing tags. As discussed before in other issues/pull requests, I believe that semantic scope names are better, even if they look ugly with your favorite theme, because they encourage theme designers to do it right as well.

I hope there is a better solution available or at least we should be aiming towards getting the issue fixed, not apply temporary (read: permanent) hacks one after another without a plan to remove them later. Fixing it manually in CSS should do in the meanwhile, I can post the snippet if someone wants.

**Comment by Gawdl3y** [comment]
Mind sharing that CSS snippet?

**Comment by Ingramz** [comment]
Actually I came up with a better solution to the problem. Update to the latest version to see if it works for you.

**Comment by Gawdl3y** [comment]
Interesting, I thought the issue was about the syntax highlighting almost entirely breaking down within HTML parameters, not just the closing brace. This is what I see:
![image](https://cloud.githubusercontent.com/assets/279900/12401279/6e1b42e6-bdf3-11e5-8c43-392779453149.png)

I'm using the [Ax Monokai](https://atom.io/themes/ax-monokai-syntax) syntax theme.

**Comment by Ingramz** [comment]
@Gawdl3y that's just a theme that doesn't handle this corner case properly. You can try placing into one of the parameters `<?php echo asset('favicon.png'); ?>`, which is the PHP-equivalent. If I remember correctly, then Monokai only will color `echo` and rest would look like on the picture above, so it's supposed to be like that.

This issue is/was about the closing `}` characters being different color with some themes.

**Comment by Gawdl3y** [comment]
What is necessary to get the syntax theme working correctly for this? See alexbarton/atom-ax-monokai-syntax#1

**Comment by Ingramz** [comment]
@Gawdl3y depends what do you mean by "correctly". It could easily be that the author of the theme intended for it to look like this. It's not "broken", but rather "unstyled".
