### ISSUE TITLE
Blade comments not getting proper formatting

### ISSUE THREAD

**Issue by filipekiss** [jawee/language-blade#22]
As you can see in the screenshot attached, the blade comments are not getting proper formatting while double slash comments work just fine.

![screen shot 2015-06-25 at 2 34 43 am](https://cloud.githubusercontent.com/assets/48519/8347911/c187e574-1ae2-11e5-943a-739641a05777.png)

I changed syntax and theme to no avail.

Thanks.

**Comment by Ingramz** [comment]
Did you try those two lines shown in a separate file? Also it would be useful to know what's before those two lines of comments.

![screenshot_50](https://cloud.githubusercontent.com/assets/1017132/8348240/b222b640-1b19-11e5-8f2b-740282115cfd.png)

**Comment by filipekiss** [comment]
I figured what was going on. There was raw PHP code being executed on the first line and since the closing tag was in the same line as the code, the editor was not considering Blade Structures properly. Changing the closing tag to its own line solved the problem.

Thanks. :)
