### ISSUE TITLE
Expanding of CSS classes into HTML snippets doesn't work

### ISSUE THREAD

**Issue by bzx** [jawee/language-blade#24]
While in HTML file, I can write: ```.someclass``` , and with my cursor at the last position, when hitting TAB I am getting ```<div class="someclass">```. Same goes for more complete structures like ```h1.page-title``` giving me ```<h1 class="page-title">```, etc.

With Blade syntax selected this expansion doesn't work as expected, giving some strange results instead.

**Comment by Ingramz** [comment]
Are you using selector-to-tag package to achieve the expansion?

**Comment by bzx** [comment]
No, I am using Emmet. (Forgot to mention that)

On Wednesday, August 26, 2015, Indrek Ardel <notifications@github.com>
wrote:

> Are you using selector-to-tag package to achieve the expansion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jawee/language-blade/issues/24#issuecomment-135046131>
> .
>


-- 
TC@mobile

**Comment by Ingramz** [comment]
https://github.com/emmetio/emmet-atom#tab-key

My guess is that it doesn't work with PHP either.

For Blade: `text html php blade`
For PHP (but could also work for Blade): `text html php`

**Comment by bzx** [comment]
Awesome! 
The former now works flawlessly in .blade!
However in .php file, outside the PHP block, expanding of HTML abbrevs is kinda impaired, e.g. class expansion doesn't quite work, as expanding of PHP kicks in. I only need to have .blade sorted out, though. I'll try to check out some alternatives to Emmet.
Thanks!
