### ISSUE TITLE
Syntax off when using @​parent tag

### ISSUE THREAD

**Issue by martinbean** [jawee/language-blade#27]
As the title says, syntax highlighting goes awry if using a @​parent tag in a Blade template:

![screen shot 2015-09-19 at 18 21 47](https://cloud.githubusercontent.com/assets/167312/9977347/9f131da8-5efb-11e5-93a7-66bd778771a0.png)

**Comment by Ingramz** [comment]
This is an issue with HTML grammar, I'll open an issue there in case one doesn't exist yet.

**Comment by martinbean** [comment]
@Ingramz Ah, sorry!

**Comment by Ingramz** [comment]
@martinbean I believe this is the exact issue you are experiencing https://github.com/atom/language-html/issues/82
