### ISSUE TITLE
Highlight custom blade directives?

### ISSUE THREAD

**Issue by JesseLeite** [jawee/language-blade#31]
Is it possible to highlight [custom blade directives](http://laravel.com/docs/5.2/blade#extending-blade)?

**Comment by Ingramz** [comment]
@JesseLeite in fact they are already highlighted, but probably not with your syntax theme. Try Atom Dark syntax theme for a moment to verify. We've had this issue before, but there's really no good solution for that.

We could make it work with a broader range of themes out of the box, but we'll probably lose the [semantic values of grammar scopes](https://manual.macromates.com/en/language_grammars#naming_conventions) (eg what a certain chunk of is named).

**Comment by JesseLeite** [comment]
@Ingramz Ah yes. I'm actually using [my own theme](https://atom.io/themes/an-old-hope-syntax). I'll look into it thanks.

Also with Atom Dark, I assume it's intentional that custom Blade directives are highlighted in a different colour than stock Laravel Blade directives?

![example](https://beemapp.s3-eu-west-1.amazonaws.com/af58446a-69e8-417d-b5ac-1652a4837f93.jpg)

**Comment by JesseLeite** [comment]
A quick followup.  Thanks for the info.  Fixed in my theme :)

That said, I notice that language-blade doesn't add `.source.blade` scope like other grammars use `.source.language`.  I think it's cleaner for themes to nest styles within `.source.language` scope, so that they can ensure no conflict with other language specific scopes.  In the case of `.blade`, I'm not sure there would be conflicts with other grammars :P  Just a thought though.

**Comment by Ingramz** [comment]
I see you have removed your "thought". I think it is a thing to look into and see if it is suitable for this package.

It would be interesting to hear whether semantically correct grammar scope names are a good thing for syntax highlighting themes in terms of cross-grammar compatibility (whether the result looks consistent across grammars or does it also depend on how the language itself is structured).

**Comment by JesseLeite** [comment]
Haha. As I looked into other themes, I started second guessing my thought. I guess you still got email notification.

Anyway, blade specific class names do allow for more readable CSS.  However, less themes will properly implement blade specific styles, because they have to go out of their way to cater to language-blade (and all the other custom grammars out there).  It's a big job for a themer.

If language-blade applied common cross-grammar CSS classes, then most any theme could half decently highlight blade directives out-of-the-box, without having to know about language-blade.  For example, you could treat a blade directive as an embedded function maybe?  I haven't thought that deeply about implementation.  Then you apply .scope.blade to everything blade specific, which allows the themer to specifically style via something like .scope.blade.embedded.function.  Again, just an example.  Not saying blade directives should be treated as embedded functions specifically.

Your thoughts?

**Comment by Ingramz** [comment]
I don't want the grammar scope names in this package to be something that every theme developer had to take those into account with just this language in mind, but be generic enough that if most of the basic selectors were covered, it would look good enough. The .blade scope should be something that were only to be used if something doesn't look right and the theme designer wanted to fix that specifically for Blade.

Designing grammar scope names around existing themes is something that I'd like to avoid (it's like designing a theme around one language). I have nothing against using a more suitable scope name from the documentation linked above and perhaps even some widely used undocumented ones, if it follows the general guidelines.

As far as implementation goes, this needs to be thought through. Also another question is how to test that the new scope names in general are better with different themes.

**Comment by JesseLeite** [comment]
Yeah all good points.  I agree about using .blade scope if themer needs to fix something specifically for blade.  I think we're agreeing on most points.

**Comment by Ingramz** [comment]
@JesseLeite just checking if you have any new ideas regarding improving the grammar scope names. I would be comfortable with incorporating elegant solutions which exist in other well maintained grammars.

**Comment by Ingramz** [comment]
Closing as it seems to be ok.

**Comment by JesseLeite** [comment]
Sorry @Ingramz I'm not sure.  I haven't had time to theme for a while.  Might revisit later, thank you!
