### ISSUE TITLE
Setting to disable blade comment

### ISSUE THREAD

**Issue by tuurbo** [jawee/language-blade#34]
An option to disable blade comments would be awesome.

For now i have to remove the below from language-blade.cson

```
'.text.html.php.blade':
  'editor':
    'commentStart': '{{-- '
    'commentEnd': ' --}}'
```

**Comment by Ingramz** [comment]
@tuurbo please try the latest release and let me know if this was what you were looking for. You can disable Blade comments by unticking the option from package settings.

**Comment by tuurbo** [comment]
@Ingramz That worked great, thank you!
