### ISSUE TITLE
Enable `{!! ... !!}` For Raw Output

### ISSUE THREAD

**Issue by mikebronner** [jawee/language-blade#38]
The `{!! ... !!}` raw output tags don't seem to work the same way as the `{{ ... }}` when invoked. Not quite sure why, still investigating.

**Comment by Ingramz** [comment]
Their behavior should be identical. If it only happens in a specific file, you can try stripping away any code that precedes it.

**Comment by mikebronner** [comment]
It's possibly a conflict with another plugin, something I need to investigate more. The behavior I'm seeing is that when I type the opening `{!!` I only get a closing `}`, instead of ` !!}`.

**Comment by Ingramz** [comment]
If you type `{`, the [bracket-matcher](https://github.com/atom/bracket-matcher) package will type in `}` for you.

Fortunately there seems to be a [feature request](https://github.com/atom/bracket-matcher/issues/182) there already to customize bracket behavior per language. That feature request might need a little expansion if you wanted `{` to be completed to `{!! | !!}`.

**Comment by Ingramz** [comment]
I'm gonna close this as the issue is too vague. I'll reopen if we can get some sort of intended behavior described here.
