### ISSUE TITLE
Can we use ctr+/ to toggle comments for blade.php code?

### ISSUE THREAD

**Issue by Allloush** [jawee/language-blade#40]
When I use ctrl+/ to toggle comment I get HTML comment which is , so can I use short cut to comment in blade file as {{-- --}}> ?

Thank you very much.

brilliant work

**Comment by Ingramz** [comment]
@Allloush it should do it already, provided you haven't turned it off from the package settings.

Make sure the following setting is ticked and the file is opened with Blade syntax highlighting:

![screenshot_6](https://cloud.githubusercontent.com/assets/1017132/14677894/4bbc99bc-071c-11e6-8abb-694a8d1bd4e7.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/1017132/14678004/b6022d3c-071c-11e6-8724-041bd246bf29.png)

If that setting is unticked, it will use the regular HTML comments

**Comment by Allloush** [comment]
@Ingramz Thank you very much. I appreciate your efforts. It works fine now
