### ISSUE TITLE
Scope names are inconsistent

### ISSUE THREAD

**Issue by jbrooksuk** [jawee/language-blade#48]
GitHub now supports highlighting of Blade files (thanks to this package 🎉) however, it's unable to highlight the `@end` scopes due to inconsistent names.

https://github.com/github/linguist/issues/3119#issuecomment-232890748

As @Alhadis suggested, the repo needs to follow the [guidelines](http://manual.macromates.com/en/language_grammars#naming_conventions) on naming conventions.

**Comment by Alhadis** [comment]
To point out the pertinent part:

> the meta scope is generally used to markup larger parts of the document. For example the entire line which declares a function would be `meta.function` and the subsets would be `storage.type`, `entity.name.function`, `variable.parameter` etc. and only the latter would be styled.

This package is assigning `meta.embedded.keyword.blade` to `@endif`, which is basically combining two elements that're expected to be separate: `meta` and `keyword`.

**Comment by Ingramz** [comment]
It has been an issue for a long time, so it doesn't come to me as a surprise.

Here is where you need to look at https://github.com/jawee/language-blade/blob/master/grammars/blade.cson#L12-L120

Submit a pull request if you think you have an idea how to solve this.
