### ISSUE TITLE
Incorrect highlighting when part of html attribute without quotes

### ISSUE THREAD

**Issue by daniel-centore** [jawee/language-blade#55]
The highlighting is incorrect when we use blade output as part of an attribute without putting it in quotes. 

Example:
`<input class="form-control" type="text" name="client_name" value={!! json_encode(e($client->name)) !!}>`

Screenshot:
![screenshot from 2016-09-17 11 35 52](https://cloud.githubusercontent.com/assets/569864/18609219/e8dbc924-7cca-11e6-98f6-b66cc0ddf94f.png)

**Comment by Ingramz** [comment]
Thanks, I'll look into it.

**Comment by Ingramz** [comment]
Initial culprit found.

https://github.com/atom/language-html/blob/d32baf880408f0281dd719be14c51d9ed451be8a/grammars/html.cson#L516-L518

This will match before Blade grammar ever gets to it. I don't know how we can inject our own expression before this nor I have interest in having to start maintaining HTML grammar too.

For now either use quotes, add a space between equals sign and anything following it or just deal with it.

**Comment by Ingramz** [comment]
This has been fixed in Atom 1.13.0.
