### ISSUE TITLE
Commented code still maintains colors

### ISSUE THREAD

**Issue by ricardofreeman** [jawee/language-blade#57]
Hi, the reason why I looked for a package to highlight blade code was precisely because of the commented code. I'd like to have it all greyed out as on other languages.

However language-blade is only showing the code greyed out if there are no colors inside:
![2016-09-22 1](https://cloud.githubusercontent.com/assets/17456791/18751731/f5dc3044-80d7-11e6-94b8-ad4c06d37d93.png)

Is this something that can be easily fixed?

Thanks in advance, cheers! :)

**Comment by Ingramz** [comment]
@ricardofreeman what you have found, is a bug. Fix incoming.
