### ISSUE TITLE
@endsection vs @stop

### ISSUE THREAD

**Issue by clroma** [jawee/language-blade#70]
@section autocopletes with @endsection insetad of @stop
The @endsection was used in Laravel 3 and it was deprecated in Laravel 4

**Comment by Ingramz** [comment]
@clroma the deprecation did not go through. Laravel 4.2+ treat `@endsection` and `@stop` equivalently.

https://github.com/laravel/framework/blob/4.2/src/Illuminate/View/Compilers/BladeCompiler.php#L330-L350

https://github.com/laravel/framework/blob/7e718491b9752198c45cfcd73630ac76df414a3c/src/Illuminate/View/Compilers/Concerns/CompilesLayouts.php#L97-L115

**Comment by clroma** [comment]
@Ingramz 
You are right.
Thanks.
