### ISSUE TITLE
@empty seems not to be working

### ISSUE THREAD

**Issue by eveningkid** [jawee/language-blade#71]
Hi,

I guess the title is quite explicit. Here's the simple code I tried using `@empty/@endempty`:

<img width="175" alt="screenshot at may 04 10-44-11" src="https://cloud.githubusercontent.com/assets/7188494/25696232/aece67f0-30b6-11e7-9b7b-ff1832938cb5.png">

I checked and you sure did add these two keywords in your `.cson` file... 
So, any idea about this issue?

Thank you! :)

**Comment by Ingramz** [comment]
Hi

Yes, I made the changes, but I didn't have a chance to test it out beforehand and so I postponed making a release.

I will do it now.

**Comment by Ingramz** [comment]
I have published v0.30.0, let me know if it works correctly for you.

**Comment by eveningkid** [comment]
Works like a charm! Perfect! :)
