### ISSUE TITLE
There is a way to add another file extesions for Blade grammar? 

### ISSUE THREAD

**Issue by nelson6e65** [jawee/language-blade#72]
In Laravel you can add extensions to blade engine (for example: `View::addExtension('layout.php', 'blade');`), but in editor there is not Syntax Highlight as blade.

**Comment by Ingramz** [comment]
Yes. Add this to your config file (you already should have `*` and core, so you must place `customFileTypes` under the exististing `core`):
```cson
"*":
  core: 
    customFileTypes:
      "text.html.php.blade": ["layout.php"]
```

**Comment by Ingramz** [comment]
Here's the manual entry for it: http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition

**Comment by nelson6e65** [comment]
Oh! Thanks! You are very kind!

Nice package! :heart:
