### ISSUE TITLE
Tag Issue! 

### ISSUE THREAD

**Issue by Encr1pt3d** [jawee/language-blade#73]
Hi friends,

I found an issue when I was programing with Atom my Laravel backend in the .blade.php files. Some tags are not colored right, look the pictures:

Look the tag "value"
https://gyazo.com/37c998e2c52df0959fcefb63d22352c3
![image](https://cloud.githubusercontent.com/assets/7103591/25808498/8e7f9ca6-340a-11e7-8a78-69798e862954.png)

https://gyazo.com/9bf97a06f498365d5042bb2e7861e235
![image](https://cloud.githubusercontent.com/assets/7103591/25808510/95d7561a-340a-11e7-8f19-ba44fdbb70de.png)

Other issue, look the "span" tag
![image](https://cloud.githubusercontent.com/assets/7103591/25808492/894f1ce8-340a-11e7-8bbd-7c7769ac568f.png)

**Comment by Ingramz** [comment]
Does the issue on last image go away if you copy that part of the code to a new document (and select Blade as language)? I think it is caused by something preceding that code.

**Comment by Ingramz** [comment]
Alright, I took a look at it and it seems that the code above is causing issues down the road, so the last image is affected by the code above.

The reason why highlighting breaks at the place you pointed is explained in #33

**Comment by Ingramz** [comment]
@Encr1pt3d I just released v0.31.0, please verify whether the issues you were having have been now solved.

**Comment by Ingramz** [comment]
Closing due to lack of feedback and inability to reproduce with newer version, assuming fixed.
