### ISSUE TITLE
code folding using language-blade

### ISSUE THREAD

**Issue by leiangelli** [jawee/language-blade#75]
I can't seem to "fold" code blocks while using "language-blade" package.
It only seem to happen when I enable language-blade, and only if the **blocks has comments**.

![29239908-0eae3eba-7f8c-11e7-997c-f0d52aab2ab6](https://user-images.githubusercontent.com/7858310/29305550-e07d378e-81cb-11e7-9e55-8dbaa40d180e.gif)

**Comment by Ingramz** [comment]
Does using HTML/PHP (not Blade) with its comments (`<!-- content -->`) do the same thing?

**Comment by leiangelli** [comment]
its still the same..
but if I disable "language-blade" folding works just fine.

![95399813c26faa0dec9600c1ef5cedca](https://user-images.githubusercontent.com/7858310/29306538-c38a7c9a-81d0-11e7-905e-216b73987b54.gif)

**Comment by Ingramz** [comment]
I fail to understand how is this any different. If two lines both end with comments, then you can only fold the first line, which hides the second line only. If I use similar pieces of code, folds appear to the same places:
![folds](https://user-images.githubusercontent.com/1017132/29307747-b9a4bb66-81ab-11e7-936e-66861cb4520c.png)

**Comment by leiangelli** [comment]
have you tried disabling language-blade?
folding works fine if its enabled..
i'm not sure where the bug is, I also tried asking atom, but they said to post it here.

**Comment by Ingramz** [comment]
I tried running `atom --safe` to avoid loading any user-installed packages, I see no difference.

Try using the same piece of code in both cases with just the comments changed, like the image I posted. That might remove some confusion. Also try working with a smaller piece of code - just enough to demonstrate the difference you are seeing.

**Comment by Ingramz** [comment]
@leiangelli any updates?

**Comment by Ingramz** [comment]
Closing due to lack of response.
