### ISSUE TITLE
kebab-case issue

### ISSUE THREAD

**Issue by AMINEDGE** [jawee/language-blade#76]
Hi I'm not sure whether this is a problem with atom html syntax or this extension,
I'm using VueJS Custom Components in my project,
but as you know MultiWord Components should be written in kebab-case form because of case insensitive html elements, and when I put my vue components, they look like this
![image](https://user-images.githubusercontent.com/13257846/30003514-56210572-90d3-11e7-93df-30f42660a366.png)
tell me if I'm wrong but I thought maybe it would be a bug or something,
Thanks

**Comment by Ingramz** [comment]
@AMINEDGE thank you for your report, it's a known issue with language-html package and there is a fix in pipeline, but it might take some time for it to get merged. I will try notifying the person responsible to try speeding up the process, but the best you can do is just wait.
