### ISSUE TITLE
Breaks @media (inline)

### ISSUE THREAD

**Issue by bytesbay** [jawee/language-blade#86]
in `@media` rules have no highlight 
![image](https://user-images.githubusercontent.com/25704307/41654416-1b2045f2-7492-11e8-89f0-3718b3f9d0cf.png)

**Comment by Ingramz** [comment]
Interesting corner case :-)

There is nothing wrong as there may or may not exist a `@media` directive. The highlighter does unfortunately know which directives exist, so it highlights all of them as part of blade.

If you wish to ignore Blade syntax, you may simply prepend another `@` to tell both the Blade and the editor that you did not mean a directive (it will not display the `@` in output):

```blade
<style>
@@media (max-width: 767px) {
  .a { color: red }
}
</style>
```

**Comment by bytesbay** [comment]
Oh thank you ! =))


20 июня 2018 г. в 14:18 Indrek Ardel <notifications@github.com> написал(а):



Interesting corner case :-)

There is nothing wrong as there may or may not exist a @media directive. The highlighter does unfortunately know which directives exist, so it highlights all of them as part of blade.

If you wish to ignore Blade syntax, you may simply prepend another @ to tell both the Blade and the editor that you did not mean a directive (it will not display the @ in output):

<style>
@@media (max-width: 767px) {
  .a { color: red }
}
</style>

**Comment by Ingramz** [comment]
I released a new version of the package which will display the first `@` as a comment to better demonstrate the use case, closing this issue for now.
